# Setup Timer To Analyse Algorithms!

In [ ]:
# A more elaborate version

import time

class TimerError(Exception):
  """A Custom exception used to report errors in use of Timer class"""

class Timer:
  def __init__(self):
    self._start_time = None
    self._elapsed_time = None

  def start(self):
    """Start a new timer"""
    if self._start_time is not None:
      raise TimerError("Timer is running. Use .stop()")
    self._start_time = time.perf_counter()
  
  def stop(self):
    """Save the elapsed time and re-initialize time"""
    if self._start_time is None:
      raise TimerError("Timer is not running. Use .start()")
    self._elapsed_time = time.perf_counter() - self._start_time
    self._start_time = None
  
  def elapsed(self):
    """Report elapsed time"""
    if self._elapsed_time is None:
      raise TimerError("Timer has not been run yet. Use .start()")
    return(self._elapsed_time)
  
  def __str__(self):
    """print() prints elapsde time"""
    return(str(self._elapsed_time))

# Sorting

## QuickSort

### Shortcomings of Merge Sort

- Extra storage can be costly!
- Recursive calls and returns, expensive.
- Mergings happens because elements in the left half need to move to the right half and vice versa.

### Idea

- Can we divide the list in such a way so that everything on the left is smaller than everything on the right?
  - No need to merge then!



### Approach_1

- Suppose the median of `L`is `m`.
- Move all values $<=m$ to left half of `L`.
  - Right half has values $>m$
- Recursively sort left and right halves
  - `L` is now sorted, no merge!
- Recurrence: $T(n) = 2T(n/2) - n$
  - Rearrange in a single pass.
- Time Complexity
  - $O(nlogn)$
- Here, we choose a random `pivot` and mark lower and upper elements. Recursively Quicksort again!

### Algorithm

- Scan the list from left to right.
- Four Segments: Pivot, Lower, Upper, Unclassified.
- Examine the first unclassified element.
  - If it is larger than the pivot, extend Upper to include this element.
  - If it is less than or equal to pivot, exchange with the first element in Upper. This extends Lower and shifts Upper by one position

In [ ]:
def quicksort(L, left, right):
  if (right - left <= 1):
    return L
  pivot = L[left]
  lower = left + 1
  upper = left + 1
  for i in range(left + 1, right):
    if L[i] > pivot: # Extend Upper
      upper += 1
    else: # Exchange L[i] with start of upper segment
      L[i], L[lower] = L[lower], L[i]
      lower += 1 # Update lower
      upper += 1 # Update Upper
  
  # Update pivot between Lower and Upper to create LOWER | PIVOT | UPPER
  L[left], L[lower - 1] = L[lower - 1], L[left]
  lower -= 1 # Update Lower

  quicksort(L, left, lower) # Sort the LOWER part
  quicksort(L, lower + 1, upper) # Sort the UPPER part

  return L

### Analysis of QuickSort

- Worst case
  - Pivot is maximum or minimum
  - Partitions are of size $0, n - 1$
  - $T(n) = n + (n-1) + ... 1$
  - $T(n)$ is $O(n^2)$
  - Already sorted array $-$ Worst case!

- However, Average case is $O(nlogn)$.

In [ ]:
import sys
sys.setrecursionlimit(2**31 - 1)

In [ ]:
import random

random.seed(2022)
input_lists = {}

input_lists["random"] = [random.randrange(100000) for i in range(5000)]
input_lists["ascending"] = [i for i in range(5000)]
input_lists["descending"] = [i for i in range(4999, -1, -1)]

t = Timer()

for i in input_lists.keys():
  l = input_lists[i][:]
  t.start()
  quicksort(l, 0, len(l))
  t.stop()
  print(i, t)

random 0.0161947940000573
ascending 1.5464928979999968
descending 2.538722294999843


### Approach_2

- Randomize choice of Pivot!

In [ ]:
import random

def quicksort(L, left, right):
  if (right - left <= 1):
    return L
  pivot = random.randint(0, right - 1)
  lower = left + 1
  upper = left + 1
  for i in range(left + 1, right):
    if L[i] > pivot: # Extend Upper
      upper += 1
    else: # Exchange L[i] with start of upper segment
      L[i], L[lower] = L[lower], L[i]
      lower += 1 # Update lower
      upper += 1 # Update Upper
  
  # Update pivot between Lower and Upper to create LOWER | PIVOT | UPPER
  L[left], L[lower - 1] = L[lower - 1], L[left]
  lower -= 1 # Update Lower

  quicksort(L, left, lower) # Sort the LOWER part
  quicksort(L, lower + 1, upper) # Sort the UPPER part

  return L

### Analysis of Approach_2

In [ ]:
import random

random.seed(2022)
input_lists = {}

input_lists["random"] = [random.randrange(100000000) for i in range(10000)]
input_lists["ascending"] = [i for i in range(10000)]
input_lists["descending"] = [i for i in range(9999, -1, -1)]

t = Timer()

for i in input_lists.keys():
  l = input_lists[i][:]
  t.start()
  quicksort(l, 0, len(l))
  t.stop()
  print(i, t)

random 0.03552606499988542
ascending 6.42362421100006
descending 11.484227608999845


# Lists And Arrays

## Python_Lists

- Append is $O(1)$

In [ ]:
t = Timer()
t.start()
l = []
for i in range(10000000):
  l.append(i)
t.stop()
print(t)

1.5015613229998053


- Insert is $O(n^2)$

In [ ]:
t = Timer()
t.start()
l = []
for i in range(300000):
  l.insert(0, i)
t.stop()
print(t)

23.086674478000532


## Searching_with_Arrays_and_Lists

### Lists

In [ ]:
def naive_search(v, L):
  """Returns true if key is found in the list by Naive Search"""
  for i in range(len(L)):
    if v == L[i]:
      return True
  return False

In [ ]:
def binary_search(key, L): # L is Sorted
  """Returns true if key is found in the list by Binary Search"""
  if L == []: # List is empty, key is not there in list
    return False
  
  m = len(L) // 2

  if key == L[m]: # If key is in midpoint of current list
    return True
  
  if key > L[m]: # If key is greater than the current middle element.
    return binary_search(key, L[m+1:])
  else:
    return binary_search(key, L[:m])

### Numpy_Arrays

In [ ]:
def naive_search_array(v, A, l, r):
  """Returns true if key is found in the array by Naive Search"""
  for i in range(l, r):
    if v == A[i]:
      return True
  return False

In [ ]:
def binary_search_array(v, A, l, r):
  """Returns true if key is found in the array by Binary Search"""
  if r - l <= 0:
    return False
  
  m = (l + r) // 2

  if v == A[m]:
    return True
  
  if v < A[m]:
    return binary_search_array(v, A, l, m)
  else:
    return binary_search_array(v, A, m+1, r)

In [ ]:
l = list(range(0, 100000, 2)) # List of Even Numbers
t = Timer() # Create an Instance of the timer object

t.start()

for i in range(3001, 13000, 2):
  v = naive_search(i, l)
t.stop()

print("Naive_Search_Lists", t)

t.start()
for i in range(3001, 13000, 2):
  v = binary_search(i, l)
t.stop()

print("Binary_Search_List", t)

Naive_Search_Lists 17.148326804000135
Binary_Search_List 0.8598581899996134


In [ ]:
import numpy as np

my_array = np.arange(0, 100000, 2)
t = Timer()

t.start()
for i in range(3001, 5000, 2):
  v = naive_search_array(i, my_array, 0, np.prod(my_array.shape))
t.stop()

print("Naive_Search_Array", t)

t.start()
for i in range(3001, 13000, 2):
  v = binary_search_array(i, my_array, 0, np.prod(my_array.shape))
t.stop()

print("Binary_Search_Array", t)

Naive_Search_Array 13.29835367800024
Binary_Search_Array 0.14629965700078174


### Questions

- Binary Search in arrays is much faster than in lists
- Why is naive search in arrays slower than in lists?

## Sorting_With_Arrays_And_Lists

### Selection_Sort

#### Selection_Sort_List

In [ ]:
def SelectionSortList(L):
   n = len(L)
   if n < 1:
      return(L)
   for i in range(n):
      # Assume L[:i] is sorted
      mpos = i  
      # mpos is position of minimum in L[i:]
      for j in range(i+1,n):
        if L[j] < L[mpos]:
           mpos = j
      # L[mpos] is the smallest value in L[i:]
      (L[i],L[mpos]) = (L[mpos],L[i])
      # Now L[:i+1] is sorted
   return(L)

#### Selection_Sort_Array

In [ ]:
def SelectionSortArray(A):
   n = np.prod(A.shape)
   if n < 1:
      return(A)
   for i in range(n):
      # Assume A[:i] is sorted
      mpos = i  
      # mpos is position of minimum in A[i:]
      for j in range(i+1,n):
        if A[j] < A[mpos]:
           mpos = j
      # A[mpos] is the smallest value in A[i:]
      (A[i],A[mpos]) = (A[mpos],A[i])
      # Now A[:i+1] is sorted
   return(A)

***Question:*** Why is selection sort slower on arrays than on lists?

In [ ]:
import random
import numpy as np
print("Selection_Sort_Lists\n")
random.seed(2021)
inputlists = {}
inputlists["random"] = [random.randrange(100000) for i in range(10000)]
inputlists["ascending"] = [i for i in range(10000)]
inputlists["descending"] = [i for i in range (9999,-1,-1)]
t = Timer()
for k in inputlists.keys():
    tmplist = inputlists[k][:]
    t.start()
    SelectionSortList(tmplist)
    t.stop()
    print(k,t)

print("\nSelection_Sort_Arrays\n")
inputarrays = {}
inputarrays["random"] = np.arange(10000)
for i in range(10000):
    inputarrays["random"][i] = random.randrange(100000)
inputarrays["ascending"] = np.arange(10000)
inputarrays["descending"] = np.arange(9999,-1,-1)
t = Timer()
for k in inputarrays.keys():
    tmparray = inputarrays[k][:]
    t.start()
    SelectionSortArray(tmparray)
    t.stop()
    print(k,t)

Selection_Sort_Lists

random 4.319338629000413
ascending 4.1922265110006265
descending 4.479455159998906

Selection_Sort_Arrays

random 11.601615706000302
ascending 11.884914026999468
descending 12.066124184999353


### Insertion_Sort

#### Insertion_Sort_List

In [ ]:
def InsertionSortList(L):
   n = len(L)
   if n < 1:
      return(L)
   for i in range(n):
      # Assume L[:i] is sorted
      # Move L[i] to correct position in L[:i]
      j = i
      while(j > 0 and L[j] < L[j-1]):
        (L[j],L[j-1]) = (L[j-1],L[j])
        j = j-1
      # Now L[:i+1] is sorted
   return(L)

#### Insertion_Sort_Array

In [ ]:
def InsertionSortArray(A):
   n = np.prod(A.shape)
   if n < 1:
      return(A)
   for i in range(n):
      # Assume A[:i] is sorted
      # Move A[i] to correct position in A[:i]
      j = i
      while(j > 0 and A[j] < A[j-1]):
        (A[j],A[j-1]) = (A[j-1],A[j])
        j = j-1
      # Now A[:i+1] is sorted
   return(A)

#### Insertion sort preformance
- On already sorted input, performance is very good
- On reverse sorted input, performance is worse than selection sort

In [ ]:
import random
import numpy as np

print("Insertion_Sort_Lists\n")
random.seed(2021)
inputlists = {}
inputlists["random"] = [random.randrange(100000) for i in range(10000)]
inputlists["ascending"] = [i for i in range(10000)]
inputlists["descending"] = [i for i in range (9999,-1,-1)]
t = Timer()
for k in inputlists.keys():
    tmplist = inputlists[k][:]
    t.start()
    InsertionSortList(tmplist)
    t.stop()
    print(k,t)

print("\nInsertion_Sort_Arrays\n")
inputarrays = {}
inputarrays["random"] = np.arange(10000)
for i in range(10000):
    inputarrays["random"][i] = random.randrange(100000)
inputarrays["ascending"] = np.arange(10000)
inputarrays["descending"] = np.arange(9999,-1,-1)
t = Timer()
for k in inputarrays.keys():
    tmparray = inputarrays[k][:]
    t.start()
    InsertionSortArray(tmparray)
    t.stop()
    print(k,t)

Insertion_Sort_Lists

random 8.92390286599948
ascending 0.001614929000425036
descending 17.406479404000493

Insertion_Sort_Arrays

random 19.02291744300055
ascending 0.0031277840007533086
descending 42.17288534299951


***Question:*** Why is insertion sort slower on arrays than on lists?

### Merge_Sort

#### Merge_Sort_List

In [ ]:
def mergeList(A,B):
  (m,n) = (len(A),len(B))
  (C,i,j,k) = ([],0,0,0)
  while k < m+n:
    if i == m:
      C.append(B[j])
      (j,k) = (j+1,k+1)
    elif j == n:
      C.append(A[i])
      (i,k) = (i+1,k+1)
    elif A[i] < B[j]:
      C.append(A[i])
      (i,k) = (i+1,k+1)
    else:
      C.append(B[j])
      (j,k) = (j+1,k+1)
  return(C)

def mergesortList(L):
  n = len(L)

  if n <= 1:
     return(L)
  
  Left = mergesortList(L[:n//2])
  Right = mergesortList(L[n//2:])

  Lsorted = mergeList(Left,Right)

  return(Lsorted)

#### Merge_Sort_Arrays

In [ ]:
def mergeArray(A,B):
  (m,n) = (np.prod(A.shape),np.prod(B.shape))
  (C,i,j,k) = (np.zeros(m+n,dtype=int),0,0,0)
  while k < m+n:
    if i == m:
      C[k] = B[j]
      (j,k) = (j+1,k+1)
    elif j == n:
      C[k] = A[i]
      (i,k) = (i+1,k+1)
    elif A[i] < B[j]:
      C[k] = A[i]
      (i,k) = (i+1,k+1)
    else:
      C[k] = B[j]
      (j,k) = (j+1,k+1)
  return(C)

def mergesortArray(A,l,r):
  if r-l <= 1:
    B = np.array(A[l:r])
    return(B)
    
  mid = (l+r)//2
  
  L = mergesortArray(A,l,mid)
  R = mergesortArray(A,mid,r)

  B = mergeArray(L,R)

  return(B)

In [ ]:
import random
import numpy as np

print("Merge_Sort_Lists\n")
random.seed(2021)
inputlists = {}
inputlists["random"] = [random.randrange(100000000) for i in range(1000000)]
inputlists["ascending"] = [i for i in range(1000000)]
inputlists["descending"] = [i for i in range (999999,-1,-1)]
t = Timer()
for k in inputlists.keys():
    tmplist = inputlists[k][:]
    t.start()
    mergesortList(tmplist)
    t.stop()
    print(k,t)

print("\nMerge_Sort_Arrays\n")
inputarrays = {}
inputarrays["random"] = np.arange(1000000)
for i in range(1000000):
    inputarrays["random"][i] = random.randrange(100000000)
inputarrays["ascending"] = np.arange(1000000)
inputarrays["descending"] = np.arange(999999,-1,-1)
t = Timer()
for k in inputarrays.keys():
    tmparray = inputarrays[k][:]
    t.start()
    mergesortArray(tmparray,0,1000000)
    t.stop()
    print(k,t)

Merge_Sort_Lists

random 9.304844260001119
ascending 7.18981144099962
descending 7.406235430999004

Merge_Sort_Arrays

random 39.716200221999316
ascending 35.46264583800075
descending 37.522356953999406


### Quick_Sort

#### Quick_Sort_List

In [ ]:
def quicksortList(L, left, right):
  if (right - left <= 1):
    return L
  pivot = L[left]
  lower = left + 1
  upper = left + 1
  for i in range(left + 1, right):
    if L[i] > pivot: # Extend Upper
      upper += 1
    else: # Exchange L[i] with start of upper segment
      L[i], L[lower] = L[lower], L[i]
      lower += 1 # Update lower
      upper += 1 # Update Upper
  
  # Update pivot between Lower and Upper to create LOWER | PIVOT | UPPER
  L[left], L[lower - 1] = L[lower - 1], L[left]
  lower -= 1 # Update Lower

  quicksort(L, left, lower) # Sort the LOWER part
  quicksort(L, lower + 1, upper) # Sort the UPPER part

  return L

#### Quick_Sort_Array

In [ ]:
def quicksortArray(A,l,r):  # Sort A[l:r]
  if (r - l <= 1):
    return(A)
  (pivot,lower,upper) = (A[l],l+1,l+1)
  for i in range(l+1,r):
    if A[i] > pivot:  # Extend upper segment
      upper = upper+1
    else:  # Exchange L[i] with start of upper segment
      (A[i], A[lower]) = (A[lower], A[i])
      # Shift both segments
      (lower,upper) = (lower+1,upper+1)
  # Move pivot between lower and upper
  (A[l],A[lower-1]) = (A[lower-1],A[l])
  lower = lower-1
  # Recursive calls
  quicksortArray(A,l,lower)
  quicksortArray(A,lower+1,upper)
  return(A)

In [ ]:
import random
import numpy as np
print("Quick_Sort_List\n")
random.seed(2021)
inputlists = {}
inputlists["random"] = [random.randrange(100000000) for i in range(1000000)]
inputlists["ascending"] = [i for i in range(20000)]
inputlists["descending"] = [i for i in range (19999,-1,-1)]
t = Timer()
for k in inputlists.keys():
    tmplist = inputlists[k][:]
    t.start()
    quicksortList(tmplist,0,len(tmplist))
    t.stop()
    print(k,t)

print("\nQuick_Sort_Array\n")
inputarrays = {}
inputarrays["random"] = np.arange(1000000)
for i in range(1000000):
    inputarrays["random"][i] = random.randrange(100000000)
inputarrays["ascending"] = np.arange(20000)
inputarrays["descending"] = np.arange(19999,-1,-1)
t = Timer()
for k in inputarrays.keys():
    tmparray = inputarrays[k][:]
    t.start()
    quicksortArray(tmparray,0,np.prod(tmparray.shape))
    t.stop()
    print(k,t)

Quick_Sort_List

random 6.508223352000641
ascending 29.416329518000566
descending 51.31639829999949

Quick_Sort_Array

random 10.525607249999666
ascending 46.952226466000866
descending 103.27215891800006


#### Quicksort performance
- Random input of size $10^7$
    - Compare with merge sort on $10^7$ random input
- Sorted inputs of size $2 \times 10^4$

## Linked_List

- Typically a sequence of nodes
- Let's implement this idea in Python

### Single_Linked_List

- Each node has a value and an address to the next element

In [ ]:
class Node:
  def __init__(self, v = None):
    self.value = v
    self.next = None
    return
  
  def is_empty(self):
    if self.value == None:
      return True
    else:
      return False
  
class singly_linked_list:
  def __init__(self):
    self.head = None
  
  def append(self, v):
    """Inserts element at the end of the list"""
    if self.is_empty():
      self.value = v
    elif self.next == None:
      self.next = Node(v)
    else:
      self.next.append(v)
    return
  
  def append_iterative(self, v):
    """Inserts element at the end of the list"""
    if self.is_empty():
      self.value = v
      return
    
    temp = self
    while(temp.next != None):
      temp = temp.next
    
    temp.next = Node(v)
    return
  
  def insert(self, v):
    """Insert element at the front of the list"""
    if self.is_empty():
      self.value = v
      return
    
    new_node = Node(v)

    self.value, new_node.value = new_node.value, self.value
    self.next, new_node.next = new_node, self.next

    return
  
  def delete(self, v):
    """Deletes value v from the list"""
    if self.is_empty():
      return
    
    if self.value == v:
      self.value = None
      if self.next != None:
        self.value = self.next.value
        self.next = self.next.next
      return
    else:
      if self.next != None:
        self.next.delete(v)
        if self.next.value == None:
          self.next = None
    
    return

## List_Comprehension

In [ ]:
# Usually what we do when initializing a multidimensional list
zero_list = [0,0,0]
zero_matrix = [zero_list, zero_list, zero_list]

zero_matrix[1][1] = 1

print("Incorrect:", zero_matrix) # Wrong Output

# Using List Comprehension
zero_matrix = [[0 for i in range(3)] for j in range(3)]
zero_matrix[1][1] = 1
print("Correct:", zero_matrix)

Incorrect: [[0, 1, 0], [0, 1, 0], [0, 1, 0]]
Correct: [[0, 0, 0], [0, 1, 0], [0, 0, 0]]


## Numpy_Arrays

In [ ]:
import numpy as np

# Multidimensional Arrays shape = (m*n) -> Dimensions
zero_matrix = np.zeros(shape=(3,3))
print(zero_matrix)

# Arrays
new_array = np.array([[0,1], [1,0]])
print(new_array)

new_array = np.arange(5)
print(new_array)

# Can operate on a matrix as a whole
print("\nMatrix Operations\n")
A = np.random.randint(2022, size=(3,5))
B = np.random.randint(2021, size=(5,3))
print(f"A = {A}\n")
print(f"B = {B}\n")
print(f"A x B = {np.matmul(A, B)}")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 1]
 [1 0]]
[0 1 2 3 4]

Matrix Operations

A = [[1918  712 1485  902 1097]
 [1584  330  578  329 1733]
 [1475  548 1923  197  480]]

B = [[ 192  259 1068]
 [1815  643 1057]
 [1679 1276 1498]
 [1719  305 1267]
 [ 630   24  503]]

A x B = [[6395499 3150876 6720163]
 [3530881 1501911 4194908]
 [5147580 3259742 5526229]]


# Dictionaries

- Collection of key-value pairs.
- Random Access
  - Access time same for all keys
- Underlying storage in an array
  - Given an offset $i$, find $A[i]$ in constant time

## Concept

- Keys have to be mapped to ${0, 1, ... n-1}$
  - Given a key $k$, convert it to an offset $i$.
  - The function that does this is `Hash Function`

## Hashing

### Hash_Function

- $h: S → X$ maps a set of values $s$ to a small range of integers {$0,1,2,... n-1$}
- Typically $|X| << |S|$, but there will be collisions

#### Collisions

- $h(s) = h(s')$ for $s \neq s'$
- A good Hash Function will `minimize collisions`.

#### SHA 256

- Industry Standard Hash Function
- Used to hash large cloud files, avoid uploading duplicates to cloud storage!

[`More about SHA 256`](https://www.movable-type.co.uk/scripts/sha256.html)



### Hash Tables

- An array of size $n$ combined with a hash function.
- $h$ maps keys to {$0,1,2,3...n-1$}
- Ideally, when we create an entry for a key $k$, $A[h(k)]$ will be unused.
  - But collisions will happen if already used.
  - How to handle this?

#### Open_Addressing [Cloased_Hashing]

- Probe a sequence of alternate slots in the same way inside the array!

#### Open_Hashing

- Each slot in the array points to a list.
- Insert into the list in the given slot.